POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "firstName": "Matti",
  "lastName": "Meikäläinen",
  "age": 22,
  "password": "123456",
  "field": "IT"
}